# Paths for project
prompt_file_path: prompts.json
uploaded_gpt_files: uploaded_gpt_files.json

pdf_folder: ../Data/PDFs/
result_folder: ../Data/Results/
csv_folder: "../Data/CSVs/"



valid_models:
  - gpt-4o
  - gpt-4o-mini
  - gpt-4-turbo
  - gemini-2.0-flash-exp
  - gemini-1.0-pro
  - gemini-1.5-flash
  - o1-preview
  - deepseek-r1:32b
  - deepseek-chat
  - gemini-2.0-pro-exp-02-05
  - gemini-1.5-pro-latest
  - gemini-2.5-pro-exp-03-25