# Paths for project

#Static Resources
prompt_file_path: resources/prompts.json
uploaded_gpt_files: resources/uploaded_gpt_files.json
basic_prompt_file_path: D:\dev\github\Study-Evaluation-Pipeline\resources\base_prompt.json

#Default Inputs
pdf_folder: data/input/pdfs/main/
standard_csv_responses: resources/csv/correct_answers.CSV
standard_csv_responses_7abc_combined: resources/csv/correct_answers_combined.CSV

#Output Paths
result_folder: data/output/runs/main/
adjusted_prompts: data/output/prompts/main/
csv_folder: data/output/csvs/



valid_models:
  # aliases
  - gpt-4o
  - gpt-4o-mini
  - gpt-4-turbo
  - gemini-2.0-flash-exp
  - gemini-1.0-pro
  - gemini-1.5-pro
  - gemini-1.5-flash
  - gemini-1.5-pro-latest
  - o1-preview
  - deepseek-r1:32b
  - deepseek-chat
  - gemini-2.5-pro
  #specific models
  - gemini-2.0-pro-exp-02-05
  - gemini-2.5-pro-exp-03-25
  - gemini-1.5-pro-002
  - gpt-4o-2024-08-06 #use this for gpt-4o
  - gpt-4o-2024-11-20
  - gpt-4o-2024-05-13
  #test model
  - test
  - test-exception